export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as PortfolioPage } from './PortfolioPage/PortfolioPage'
export { default as AboutMePage } from './AboutMePage/AboutMePage'
export { default as ContactPage } from './ContactPage/ContactPage'