export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Landing } from './Landing/Landing'
export { default as About } from './About/About'
export { default as Skills } from './Skills/Skills'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Blog } from './Blog/Blog'
export { default as SingleBlog } from './Blog/SingleBlog/SingleBlog'